version: '3.8'

services:
  backend:
    build:
      context: ./LoginKit_backend_code  # Path to your backend code
    container_name: login-kit-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis/redis-stack:latest
    container_name: login-kit-redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
